os:
  editCommand: "nvim"
  editCommandTemplate: 'nvr -l --remote {{filename}}'
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --line-numbers --dark --paging=never
