os:
  editCommandTemplate: "nvr -cc q --remote {{filename}}"
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
git:
  paging:
    colorArg: always
    pager: delta --line-numbers --dark --paging=never
  log:
    order: default
