os:
  editCommand: "nvim"
  editCommandTemplate: 'nvr --remote-send "q" {{filename}}'
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --line-numbers --dark --paging=never
